// Generated by CoffeeScript 1.3.3
(function() {
  var help, init_app, make_target;

  help = ["Initializes client side application structure.\nSets initial folders structure.\n\nParameters:\n    - app_root - base path for application compiling.\n    - js_path - path where result js will be stored."];

  make_target = require('../lib/target').make_target;

  init_app = function(ctx, cb) {
    return typeof cb === "function" ? cb('stop') : void 0;
  };

  module.exports = make_target("csinit", init_app, help);

}).call(this);
