// Generated by CoffeeScript 1.3.3
(function() {
  var Gettext, fs, help, localize, localize_run, make_target, path, say, scream, shout, whisper, _ref;

  help = ["<localize> command performs localization of javascript files.\n\nParameters:\n    --src      - jsFile or dir for translation.\n    --locales  - directory with locales for translation."];

  fs = require('fs');

  path = require('path');

  Gettext = require('../lib/gettext');

  make_target = require('../lib/target').make_target;

  localize_run = require('../lib/localizer').localize_run;

  _ref = (require('../lib/logger'))("Localizer>"), say = _ref.say, shout = _ref.shout, scream = _ref.scream, whisper = _ref.whisper;

  localize = function(ctx, cb) {
    var filename, locales_root_dir, _ref1;
    locales_root_dir = ((_ref1 = ctx.own_args.locales) != null ? _ref1.length : void 0) ? path.resolve(ctx.own_args.locales) : void 0;
    filename = ctx.own_args.src;
    if ((filename != null) && !fs.existsSync(filename)) {
      shout("Bad file " + filename + ", it does not exist");
      ctx.print_help();
    }
    if (!(locales_root_dir && filename)) {
      return ctx.print_help();
    }
    return localize_run(locales_root_dir, filename, cb);
  };

  module.exports = make_target("localize", localize, help);

}).call(this);
