// Generated by CoffeeScript 1.6.1
(function() {
  var CLEAN_ALL_PASS, help, make_target, menu, waiter;

  CLEAN_ALL_PASS = 'allyesiamsure';

  help = ["Prepares your coffee according to the menu selection.\nPrints current menu if called without paramaters.\n\nParameters:\n\n    --new=<name> <any other cafe options>\n        saves all cafe options to the menu under the name <name>\n\n    --expire <name>\n        removes specified dish from the menu\n        expires the whole menu if <name> == " + CLEAN_ALL_PASS + "\n\n    --show <name>\n        shows ingredients\n\n    --justatea <name>\n        just prints commands in plain text\n\n    <name>\n        serves ordered menu for your pleasure.\n        Bon appetite!\n\n    --help\n        this help\n\n    prints current menu if called without arguments."];

  make_target = require('../lib/target').make_target;

  menu = require('../lib/menu');

  waiter = function(ctx, cb) {
    var arg1, arg2, _ref;
    _ref = Object.keys(ctx.full_args).filter(function(i) {
      return i !== 'global' && i !== 'menu';
    }), arg1 = _ref[0], arg2 = _ref[1];
    if (ctx.own_args["new"]) {
      return menu._do_new_menu(ctx.own_args["new"], ctx, cb);
    } else if ((ctx.own_args.hasOwnProperty('expire')) && arg1) {
      return menu._do_expire_menu(arg1, ctx, cb);
    } else if ((ctx.own_args.hasOwnProperty('show')) && arg1) {
      return menu._do_show_menu(arg1, ctx, cb);
    } else if ((ctx.own_args.hasOwnProperty('justatea')) && arg1) {
      return menu._do_just_tea(arg1, ctx, cb);
    } else if (ctx.own_args.hasOwnProperty('help')) {
      return menu._do_help(ctx, cb);
    } else if (arg1) {
      return menu._do_serve_menu(arg1, ctx, cb);
    } else {
      return menu._do_default(ctx, cb);
    }
  };

  module.exports = make_target("menu", waiter, help);

}).call(this);
