// Generated by CoffeeScript 1.3.3
(function() {
  var help, make_skelethon, make_target, skelethon;

  help = ["This command is used for creating init module structure.\nThe logic of skelethon creation is defined by appropriate adaptor."];

  make_target = require('../lib/target').make_target;

  make_skelethon = require('../lib/skelethon/skelethon').make_skelethon;

  skelethon = function(ctx, cb) {
    return typeof cb === "function" ? cb('stop') : void 0;
  };

  module.exports = make_target('skelethon', skelethon, help, true);

}).call(this);
