// Generated by CoffeeScript 1.4.0
(function() {
  var ADAPTORS_LIB, ADAPTORS_PATH, get_plugins, is_dir, is_file, path, say, scream, shout, whisper, _ref, _ref1, _ref2;

  path = require('path');

  _ref = require('./utils'), is_file = _ref.is_file, is_dir = _ref.is_dir, get_plugins = _ref.get_plugins;

  _ref1 = (require('./logger'))("libadaptor>"), say = _ref1.say, shout = _ref1.shout, scream = _ref1.scream, whisper = _ref1.whisper;

  _ref2 = require('../defs'), ADAPTORS_PATH = _ref2.ADAPTORS_PATH, ADAPTORS_LIB = _ref2.ADAPTORS_LIB;

  module.exports = function() {
    var adaptors_names;
    adaptors_names = get_plugins(ADAPTORS_PATH);
    return adaptors_names.map(function(a_name) {
      try {
        return require(path.join(ADAPTORS_LIB, a_name));
      } catch (e) {
        scream("Can't load adaptor '" + a_name + "': " + e);
        throw e;
      }
    });
  };

}).call(this);
