// Generated by CoffeeScript 1.3.3
(function() {
  var ADAPTORS_LIB, ADAPTORS_PATH, ADAPTOR_FN, JS_EXT, fs, get_plugins, is_dir, is_file, path, say, scream, shout, whisper, _ref, _ref1, _ref2,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  path = require('path');

  fs = require('fs');

  _ref = require('./utils'), is_file = _ref.is_file, is_dir = _ref.is_dir, get_plugins = _ref.get_plugins;

  _ref1 = (require('./logger'))("libadaptor>"), say = _ref1.say, shout = _ref1.shout, scream = _ref1.scream, whisper = _ref1.whisper;

  _ref2 = require('../defs'), ADAPTORS_PATH = _ref2.ADAPTORS_PATH, ADAPTOR_FN = _ref2.ADAPTOR_FN, ADAPTORS_LIB = _ref2.ADAPTORS_LIB, JS_EXT = _ref2.JS_EXT;

  module.exports = function() {
    var fn_pattern;
    fn_pattern = "" + ADAPTOR_FN + JS_EXT;
    return (fs.readdirSync(ADAPTORS_PATH)).map(function(p) {
      return path.join(ADAPTORS_PATH, p);
    }).filter(function(fn) {
      return (is_dir(fn)) && __indexOf.call(fs.readdirSync(fn), fn_pattern) >= 0;
    }).map(function(d) {
      return require(path.join(d, fn_pattern));
    });
  };

}).call(this);
