// Generated by CoffeeScript 1.4.0
(function() {
  var domonad, error_monad;

  domonad = function(_arg, functions) {
    var bind, result;
    result = _arg.result, bind = _arg.bind;
    return function(init_value) {
      var f0;
      f0 = bind(result(init_value), functions[0]);
      return ([f0].concat(functions.slice(1))).reduce(function(a, b) {
        return bind(a, b);
      });
    };
  };

  error_monad = {
    bind: function(_arg, mf) {
      var err, mv;
      err = _arg[0], mv = _arg[1];
      if (!err) {
        return mf(mv);
      } else {
        return [err, mv];
      }
    },
    result: function(mv) {
      return [void 0, mv];
    }
  };

  module.exports = {
    domonad: domonad,
    error_monad: error_monad
  };

}).call(this);
