// Generated by CoffeeScript 1.6.1
(function() {
  var fs, get_mtime, mkdirp, path;

  fs = require('fs');

  path = require('path');

  mkdirp = require('mkdirp');

  get_mtime = require('./utils').get_mtime;

  exports.get_modules_cache = function(cache_path) {
    var get_fn;
    get_fn = function(module_name) {
      return path.join(cache_path, module_name + '.cache');
    };
    return {
      get: function(module_name) {
        return JSON.parse(fs.readFileSync(get_fn(module_name)));
      },
      save: function(cache) {
        var module_name, write_file;
        module_name = get_fn(cache.module.name);
        write_file = function(cached_mod) {
          return fs.writeFileSync(get_fn(cached_mod.module.name), JSON.stringify(cached_mod));
        };
        if (path.existsSync(path.dirname(module_name))) {
          return write_file(cache);
        } else {
          return mkdirp(path.dirname(module_name), function(err) {
            if (err) {
              throw "Can not create cache dirrectory " + err;
            }
            return write_file(cache);
          });
        }
      },
      get_cached_file_path: function(module_name) {
        return get_fn(module_name);
      },
      get_cache_mtime: function(module) {
        try {
          return get_mtime((get_fn(module.name)).toString());
        } catch (e) {
          return 0;
        }
      }
    };
  };

}).call(this);
