// Generated by CoffeeScript 1.4.0
(function() {
  var Dependency, Package, Stitch, compilers, eco, fs, logger, path, say, scream, shout, stitch, toArray, uglify, whisper, _ref;

  fs = require('fs');

  eco = require('eco');

  uglify = require('uglify-js');

  path = require('path');

  compilers = require('./compilers');

  stitch = require('../../assets/stitch');

  Dependency = require('./dependency');

  Stitch = require('./stitch');

  toArray = require('./utils').toArray;

  logger = require('../lib/logger');

  _ref = logger("Package>"), say = _ref.say, shout = _ref.shout, scream = _ref.scream, whisper = _ref.whisper;

  Package = (function() {

    function Package(config) {
      if (config == null) {
        config = {};
      }
      this.identifier = config.identifier;
      this.libs = toArray(config.libs);
      this.paths = toArray(config.paths);
      this.dependencies = toArray(config.dependencies);
    }

    Package.prototype.compileModules = function() {
      this.dependency || (this.dependency = new Dependency(this.dependencies));
      this.stitch = new Stitch(this.paths);
      this.modules = this.dependency.resolve().concat(this.stitch.resolve());
      return stitch({
        identifier: this.identifier,
        modules: this.modules
      });
    };

    Package.prototype.compileLibs = function() {
      return ((function() {
        var _i, _len, _ref1, _results;
        _ref1 = this.libs;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          path = _ref1[_i];
          _results.push(fs.readFileSync(path, 'utf8'));
        }
        return _results;
      }).call(this)).join("\n");
    };

    Package.prototype.compile = function() {
      var result;
      result = [this.compileLibs(), this.compileModules()].join("\n");
      return result;
    };

    Package.prototype.createServer = function() {
      var _this = this;
      return function(env, callback) {
        return callback(200, {
          'Content-Type': 'text/javascript'
        }, _this.compile());
      };
    };

    return Package;

  })();

  module.exports = {
    compilers: compilers,
    Package: Package,
    createPackage: function(config) {
      return new Package(config);
    }
  };

}).call(this);
