// Generated by CoffeeScript 1.6.1
(function() {
  var GLOBAL, f, fsm, get_args_list, r, toArray;

  toArray = require('./utils').toArray;

  GLOBAL = 'global';

  f = function(arg) {
    if (arg.slice(0, 2) === '--') {
      return arg.split('=');
    }
    if (arg[0] === '-') {
      return [arg, true];
    }
    return arg;
  };

  fsm = function() {
    var s;
    s = GLOBAL;
    return function(i) {
      if (i[0] !== '-') {
        s = i;
        return [s, null];
      } else {
        return [s, i];
      }
    };
  };

  r = function(prev, cur) {
    var command_key, option, option_key, _name;
    prev[_name = cur[0]] || (prev[_name] = {});
    if (cur[1] != null) {
      option = f(cur[1]);
      command_key = cur[0];
      option_key = option[0].replace('--', '').replace('-', '');
      if (!prev[command_key].hasOwnProperty(option_key)) {
        prev[command_key][option_key] = option[1];
      } else {
        prev[command_key][option_key] = toArray(prev[command_key][option_key]);
        prev[command_key][option_key].push(option[1]);
      }
    }
    return prev;
  };

  get_args_list = function(argv) {
    var ret;
    ret = argv.slice(2).map(fsm()).reduce(r, {});
    if (!ret.hasOwnProperty(GLOBAL)) {
      ret[GLOBAL] = {};
    }
    return Object.freeze(ret);
  };

  module.exports = get_args_list;

}).call(this);
