// Generated by CoffeeScript 1.6.1
(function() {
  var fs;

  fs = require('fs');

  exports.put_to_tmp_storage = function(key, data, cb) {
    return fs.writeFile(key, data, function(err) {
      if (err) {
        cb(err);
      }
      return typeof cb === "function" ? cb(null, key) : void 0;
    });
  };

}).call(this);
