// Generated by CoffeeScript 1.3.3
(function() {
  var LOG_PREFIX, blue, cyan, green, nocolor, red, yellow, _ref,
    __slice = [].slice;

  LOG_PREFIX = 'UI>';

  _ref = (require('./logger'))(), green = _ref.green, yellow = _ref.yellow, red = _ref.red, blue = _ref.blue, cyan = _ref.cyan;

  nocolor = function(s) {
    return s;
  };

  module.exports = function(log_prefix) {
    var apply1, murmur, say, scream, shout, whisper;
    apply1 = function(type, color) {
      return function() {
        var a;
        a = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return console[type].apply(console, [color(log_prefix || LOG_PREFIX)].concat(a));
      };
    };
    say = apply1('log', cyan);
    shout = apply1('info', yellow);
    scream = apply1('error', red);
    whisper = apply1('error', red);
    murmur = apply1('log', nocolor);
    return {
      say: say,
      shout: shout,
      scream: scream,
      whisper: whisper,
      murmur: murmur
    };
  };

}).call(this);
