// Generated by CoffeeScript 1.3.1
(function() {
  var Minifier, Target, fs, help, is_dir, minify, minify_target, say, scream, shout, _ref;

  help = ["minify command is used for js minification", " --src - source dir with js files", " --dst - destination dir for placing minified files", " --pattern - file pattern for minification", " --file - specifies the file for minification.     ", "          if this command is specified the --src param", "          is skipped"];

  Minifier = require('../lib/minifier');

  Target = require('../lib/target');

  _ref = require('../lib/logger'), say = _ref.say, shout = _ref.shout, scream = _ref.scream;

  fs = require('fs');

  is_dir = function(fn) {
    try {
      return (fs.lstatSync(fn)).isDirectory();
    } catch (e) {
      return false;
    }
  };

  minify = function(args, cb) {
    var minifier;
    if (!is_dir(args.src) && !(args.file != null)) {
      shout("Wrong 'src' parameter for minify: '" + args.src + "'");
      process.exit(1);
    }
    if (!is_dir(args.dst) && !(args.file != null)) {
      shout("Wrong 'dst' parameter for minify: '" + args.dst + "'");
      process.exit(1);
    }
    minifier = new Minifier(args.src, args.dst, args.pattern);
    say("Starting minify ...");
    return minifier.minify(cb);
  };

  minify_target = new Target("minify", minify, help);

  module.exports = minify_target;

}).call(this);
