// Generated by CoffeeScript 1.3.3
(function() {
  var CoffeeScript, eco, p;

  CoffeeScript = require('coffee-script');

  eco = require('eco');

  p = require('path');

  exports.coffee = function() {
    return {
      match: function(path) {
        return (p.exname(path)) === '.coffee';
      },
      compile: function(path) {
        return CoffeeScript.compile(fs.readFileSync(path, 'utf8'));
      }
    };
  };

  exports.eco = function() {
    return {
      match: function(path) {
        return (p.exname(path)) === '.coffee';
      },
      compile: function(path) {
        return eco.compile(fs.readFileSync(filename, 'utf8'));
      }
    };
  };

}).call(this);
