// Generated by CoffeeScript 1.3.3
(function() {
  var CoffeeScript, eco, fs;

  CoffeeScript = require('coffee-script');

  eco = require('eco');

  fs = require('fs');

  exports.coffee = function() {
    return {
      ext: 'coffee',
      compile: function(path) {
        return CoffeeScript.compile(fs.readFileSync(path, 'utf8'));
      }
    };
  };

  exports.eco = function() {
    return {
      ext: 'eco',
      compile: function(path) {
        return eco.compile(fs.readFileSync(path, 'utf8'));
      }
    };
  };

}).call(this);
