abstract: 
    api_version: 5
    # extends:

#opts:
#    minify: false


# modules section is for registering application modules
# you can read more detailed about modules format here - https://github.com/EugeneN/cafe/wiki/recipe-file
modules:
    #- jquery: npm://commonjs-jquery


# Section for defining your bundles structure
bundles:
    bundle1:
        modules:
            #- jquery